/** Browser-only rendering of the isolated static preview as one PNG image. */
import { toBlob } from 'html-to-image';
/** Conservative cross-browser canvas edge used for one portable long image. */
export declare const MAX_LONG_IMAGE_EDGE = 16384;
/** Conservative pixel budget that avoids browser canvas allocation failures. */
export declare const MAX_LONG_IMAGE_PIXELS = 16000000;
/** Safe, user-visible failure while creating a browser-local long image. */
export declare class LongImageError extends Error {
    readonly name = "LongImageError";
}
/**
 * Resolve the largest useful image scale within conservative canvas limits.
 * @param width - preview document width in CSS pixels.
 * @param height - preview document height in CSS pixels.
 * @returns scale from one to two device-independent pixels per CSS pixel.
 */
export declare function longImageScale(width: number, height: number): number;
/**
 * Capture the current safe preview document without loading external resources.
 * @param frame - loaded same-origin preview iframe generated by the Host.
 * @param capture - injectable html-to-image implementation.
 * @returns one PNG blob.
 */
export declare function captureLongImage(frame: HTMLIFrameElement, capture?: typeof toBlob): Promise<Blob>;
/**
 * Replace a generated text extension with PNG.
 * @param filename - Host-generated local-share filename.
 * @returns long-image filename with the same date.
 */
export declare function longImageFilename(filename: string): string;
/**
 * Copy a PNG with the browser's image clipboard API.
 * @param blob - generated PNG.
 * @param clipboard - injectable browser clipboard.
 * @param ClipboardItemType - injectable browser ClipboardItem constructor.
 * @returns whether the browser accepted the image.
 */
export declare function copyLongImage(blob: Blob, clipboard?: Pick<Clipboard, 'write'> | undefined, ClipboardItemType?: typeof ClipboardItem | undefined): Promise<boolean>;
