/** Browser-only rendering of the isolated static preview as one PNG image. */
import { toBlob } from 'html-to-image'

/** Conservative cross-browser canvas edge used for one portable long image. */
export const MAX_LONG_IMAGE_EDGE = 16_384

/** Conservative pixel budget that avoids browser canvas allocation failures. */
export const MAX_LONG_IMAGE_PIXELS = 16_000_000

/** Safe, user-visible failure while creating a browser-local long image. */
export class LongImageError extends Error {
  override readonly name = 'LongImageError'
}

/**
 * Resolve the largest useful image scale within conservative canvas limits.
 * @param width - preview document width in CSS pixels.
 * @param height - preview document height in CSS pixels.
 * @returns scale from one to two device-independent pixels per CSS pixel.
 */
export function longImageScale(width: number, height: number): number {
  if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) {
    throw new LongImageError('dsh-local-share: the preview has no measurable content')
  }
  const scale = Math.min(
    2,
    MAX_LONG_IMAGE_EDGE / width,
    MAX_LONG_IMAGE_EDGE / height,
    Math.sqrt(MAX_LONG_IMAGE_PIXELS / (width * height)),
  )
  if (scale < 1) {
    throw new LongImageError('dsh-local-share: the long image exceeds browser canvas limits; select fewer turns and try again')
  }
  return scale
}

/**
 * Capture the current safe preview document without loading external resources.
 * @param frame - loaded same-origin preview iframe generated by the Host.
 * @param capture - injectable html-to-image implementation.
 * @returns one PNG blob.
 */
export async function captureLongImage(
  frame: HTMLIFrameElement,
  capture: typeof toBlob = toBlob,
): Promise<Blob> {
  const preview = frame.contentDocument
  if (preview === null) throw new LongImageError('dsh-local-share: the preview is not ready')
  await preview.fonts?.ready
  const root = preview.documentElement
  const width = Math.ceil(root.scrollWidth)
  const height = Math.ceil(root.scrollHeight)
  const scale = longImageScale(width, height)
  const backgroundColor = preview.defaultView?.getComputedStyle(root).backgroundColor || '#f5f5f7'
  const blob = await capture(root, {
    backgroundColor,
    width,
    height,
    canvasWidth: Math.ceil(width * scale),
    canvasHeight: Math.ceil(height * scale),
    pixelRatio: 1,
    skipFonts: true,
  })
  if (blob === null || blob.type !== 'image/png') {
    throw new LongImageError('dsh-local-share: the browser could not encode the long image')
  }
  return blob
}

/**
 * Replace a generated text extension with PNG.
 * @param filename - Host-generated local-share filename.
 * @returns long-image filename with the same date.
 */
export function longImageFilename(filename: string): string {
  return filename.replace(/\.(?:html|md)$/u, '.png')
}

/**
 * Copy a PNG with the browser's image clipboard API.
 * @param blob - generated PNG.
 * @param clipboard - injectable browser clipboard.
 * @param ClipboardItemType - injectable browser ClipboardItem constructor.
 * @returns whether the browser accepted the image.
 */
export async function copyLongImage(
  blob: Blob,
  clipboard: Pick<Clipboard, 'write'> | undefined = navigator.clipboard,
  ClipboardItemType: typeof ClipboardItem | undefined = globalThis.ClipboardItem,
): Promise<boolean> {
  if (clipboard === undefined || ClipboardItemType === undefined) return false
  try {
    await clipboard.write([new ClipboardItemType({ 'image/png': blob })])
    return true
  } catch {
    return false
  }
}
